USE customer_behaviour

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from shopping_data
group by gender
GO

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from shopping_data
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from shopping_data)
GO

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 
    item_purchased, 
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS "Average Product Rating"
FROM shopping_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;
GO

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT 
    shipping_type, 
    ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS "Avg Purchase Amount"
FROM shopping_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
GO

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS avg_spend,
    ROUND(SUM(CAST(purchase_amount AS DECIMAL(10,2))), 2) AS total_revenue
FROM shopping_data
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;
GO

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5
       item_purchased,
       CAST(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*) AS DECIMAL(5,2)) AS discount_rate
FROM shopping_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
GO

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM shopping_data)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;
GO

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM shopping_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM shopping_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM shopping_data
GROUP BY age_group
ORDER BY total_revenue desc;